package org.parkjw.capylinker.ui.strings

data class AppStrings(
    val language: String,
    val languageDisplayName: String,
    val appName: String,
    val settings: String,
    val addLink: String,
    val add: String,
    val apiKeyConfiguration: String,
    val apiKeyDescription: String,
    val apiKeyLabel: String,
    val apiKeyPlaceholder: String,
    val apiKeyHint: String,
    val saveApiKey: String,
    val apiKeySaved: String,
    val modelSettings: String,
    val modelLabel: String,
    val modelDescription: String,
    val languageSettings: String,
    val languageLabel: String,
    val themeSettings: String,
    val themeLabel: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val clipboardAutoAddLabel: String,
    val clipboardDetected: String,
    val clipboardMessage: String,
    val back: String,
    val cancel: String,
    val save: String,
    val enterUrl: String,
    val urlPlaceholder: String,
    val analyzing: String,
    val welcomeMessage: String,
    val quotaExceeded: String,
    val retryLater: String,
    val tip: String,
    val quotaTipMessage: String,
    val addLinkDialogDescription: String,
    val urlLabel: String,
    val linkOptions: String,
    val open: String,
    val copyUrl: String,
    val share: String,
    val delete: String,
    val search: String,
    val searchPlaceholder: String,
    val noResults: String,
    val pressBackAgainToExit: String,
    val notionPageNote: String,
    val backupAndRestore: String,
    val backupDescription: String,
    val createBackup: String,
    val restoreBackup: String,
    val backupSuccess: String,
    val restoreSuccess: String,
    val restoreFailed: String,
    val backupCreating: String,
    val restoreInProgress: String,
    val appVersion: String,
    val versionFormat: String,
    val reSummarize: String,
    val analyzingTitle: String,
    val analyzingSummary: String,
    val analysisFailedTitle: String,
    val analysisFailedSummary: String
)

// 지원 언어 목록
val SupportedLanguages = listOf(
    "en" to "English",
    "ko" to "한국어",
    "ja" to "日本語",
    "zh-CN" to "简体中文",
    "zh-TW" to "繁體中文",
    "es" to "Español",
    "fr" to "Français",
    "de" to "Deutsch",
    "ru" to "Русский",
    "pt" to "Português"
)

val EnglishStrings = AppStrings(
    language = "en",
    languageDisplayName = "English",
    appName = "CapyLinker",
    settings = "Settings",
    addLink = "Add Link",
    add = "Add",
    apiKeyConfiguration = "Gemini API Configuration",
    apiKeyDescription = "Enter your Gemini API key to enable AI-powered link analysis.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Get your API key from Google AI Studio: https://makersuite.google.com/app/apikey",
    saveApiKey = "Save API Key",
    apiKeySaved = "API Key saved successfully!",
    modelSettings = "Model Settings",
    modelLabel = "Gemini Model",
    modelDescription = "Select the Gemini model to use for analysis.",
    languageSettings = "Language Settings",
    languageLabel = "Language",
    themeSettings = "Theme Settings",
    themeLabel = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    clipboardAutoAddLabel = "Auto-add from Clipboard",
    clipboardDetected = "URL Detected",
    clipboardMessage = "Would you like to add this URL from your clipboard?",
    back = "Back",
    cancel = "Cancel",
    save = "Save",
    enterUrl = "Enter the URL to analyze:",
    urlPlaceholder = "https://example.com",
    analyzing = "Analyzing with Gemini AI...",
    welcomeMessage = "Welcome to CapyLinker",
    quotaExceeded = "API Quota Exceeded",
    retryLater = "Please try again later",
    tip = "💡 Tip",
    quotaTipMessage = "The free tier has limited requests per minute. If you hit the limit, the app will automatically retry after a short delay.",
    addLinkDialogDescription = "The link will be analyzed in the background using Gemini AI.",
    urlLabel = "URL",
    linkOptions = "Link Options",
    open = "Open",
    copyUrl = "Copy URL",
    share = "Share",
    delete = "Delete",
    search = "Search",
    searchPlaceholder = "Search links...",
    noResults = "No results found",
    pressBackAgainToExit = "Press back again to exit",
    notionPageNote = "Note: Notion pages have dynamic content. Limited information may be available.",
    backupAndRestore = "Backup & Restore",
    backupDescription = "Back up all your data including links, settings, and API key.",
    createBackup = "Create Backup",
    restoreBackup = "Restore Backup",
    backupSuccess = "Backup created successfully!",
    restoreSuccess = "Data restored successfully!",
    restoreFailed = "Failed to restore backup. Please check the file.",
    backupCreating = "Creating backup...",
    restoreInProgress = "Restoring data...",
    appVersion = "App Version",
    versionFormat = "Version %s (Build %s)",
    reSummarize = "Re-summarize",
    analyzingTitle = "Analyzing...",
    analyzingSummary = "AI analysis in progress...",
    analysisFailedTitle = "Analysis Failed",
    analysisFailedSummary = "Failed to analyze: %s"
)

val KoreanStrings = AppStrings(
    language = "ko",
    languageDisplayName = "한국어",
    appName = "CapyLinker",
    settings = "설정",
    addLink = "링크 추가",
    add = "추가",
    apiKeyConfiguration = "Gemini API 설정",
    apiKeyDescription = "AI 기반 링크 분석을 사용하려면 Gemini API 키를 입력하세요.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Google AI Studio에서 API 키를 발급받으세요: https://makersuite.google.com/app/apikey",
    saveApiKey = "API 키 저장",
    apiKeySaved = "API 키가 저장되었습니다!",
    modelSettings = "모델 설정",
    modelLabel = "Gemini 모델",
    modelDescription = "분석에 사용할 Gemini 모델을 선택하세요.",
    languageSettings = "언어 설정",
    languageLabel = "언어",
    themeSettings = "테마 설정",
    themeLabel = "테마",
    themeSystem = "시스템",
    themeLight = "라이트",
    themeDark = "다크",
    clipboardAutoAddLabel = "클립보드 자동 추가",
    clipboardDetected = "URL 감지됨",
    clipboardMessage = "클립보드의 URL을 추가하시겠습니까?",
    back = "뒤로",
    cancel = "취소",
    save = "저장",
    enterUrl = "분석할 URL을 입력하세요:",
    urlPlaceholder = "https://example.com",
    analyzing = "Gemini AI로 분석 중...",
    welcomeMessage = "CapyLinker에 오신 것을 환영합니다",
    quotaExceeded = "API 할당량 초과",
    retryLater = "잠시 후 다시 시도해주세요",
    tip = "💡 팁",
    quotaTipMessage = "무료 플랜은 분당 요청 수가 제한되어 있습니다. 제한에 도달하면 앱이 짧은 지연 후 자동으로 재시도합니다.",
    addLinkDialogDescription = "링크는 백그라운드에서 Gemini AI로 분석됩니다.",
    urlLabel = "URL",
    linkOptions = "링크 옵션",
    open = "열기",
    copyUrl = "URL 복사",
    share = "공유",
    delete = "삭제",
    search = "검색",
    searchPlaceholder = "링크 검색...",
    noResults = "검색 결과가 없습니다",
    pressBackAgainToExit = "뒤로 버튼을 한 번 더 누르면 종료됩니다",
    notionPageNote = "참고: 노션 페이지는 동적 콘텐츠로 제한된 정보만 제공될 수 있습니다.",
    backupAndRestore = "백업 및 복원",
    backupDescription = "링크, 설정, API 키를 포함한 모든 데이터를 백업합니다.",
    createBackup = "백업 생성",
    restoreBackup = "백업 복원",
    backupSuccess = "백업이 성공적으로 생성되었습니다!",
    restoreSuccess = "데이터가 성공적으로 복원되었습니다!",
    restoreFailed = "백업 복원에 실패했습니다. 파일을 확인해주세요.",
    backupCreating = "백업 생성 중...",
    restoreInProgress = "데이터 복원 중...",
    appVersion = "앱 버전",
    versionFormat = "버전 %s (빌드 %s)",
    reSummarize = "다시 요약",
    analyzingTitle = "분석 중...",
    analyzingSummary = "AI가 링크를 분석하고 있습니다...",
    analysisFailedTitle = "분석 실패",
    analysisFailedSummary = "분석에 실패했습니다: %s"
)

val JapaneseStrings = AppStrings(
    language = "ja",
    languageDisplayName = "日本語",
    appName = "CapyLinker",
    settings = "設定",
    addLink = "リンクを追加",
    add = "追加",
    apiKeyConfiguration = "Gemini API 設定",
    apiKeyDescription = "AI駆動のリンク分析を有効にするには、Gemini APIキーを入力してください。",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Google AI StudioからAPIキーを取得: https://makersuite.google.com/app/apikey",
    saveApiKey = "APIキーを保存",
    apiKeySaved = "APIキーが保存されました！",
    modelSettings = "モデル設定",
    modelLabel = "Geminiモデル",
    modelDescription = "分析に使用するGeminiモデルを選択してください。",
    languageSettings = "言語設定",
    languageLabel = "言語",
    themeSettings = "テーマ設定",
    themeLabel = "テーマ",
    themeSystem = "システム",
    themeLight = "ライト",
    themeDark = "ダーク",
    clipboardAutoAddLabel = "クリップボードから自動追加",
    clipboardDetected = "URL検出",
    clipboardMessage = "クリップボードのURLを追加しますか？",
    back = "戻る",
    cancel = "キャンセル",
    save = "保存",
    enterUrl = "分析するURLを入力:",
    urlPlaceholder = "https://example.com",
    analyzing = "Gemini AIで分析中...",
    welcomeMessage = "CapyLinkerへようこそ",
    quotaExceeded = "API割り当て超過",
    retryLater = "しばらくしてからもう一度お試しください",
    tip = "💡 ヒント",
    quotaTipMessage = "無料プランは1分あたりのリクエスト数に制限があります。制限に達すると、アプリは短い遅延後に自動的に再試行します。",
    addLinkDialogDescription = "リンクはバックグラウンドでGemini AIによって分析されます。",
    urlLabel = "URL",
    linkOptions = "リンクオプション",
    open = "開く",
    copyUrl = "URLをコピー",
    share = "共有",
    delete = "削除",
    search = "検索",
    searchPlaceholder = "リンクを検索...",
    noResults = "結果が見つかりません",
    pressBackAgainToExit = "もう一度戻るボタンを押すと終了します",
    notionPageNote = "注意: Notionページは動的コンテンツのため、限られた情報のみ利用可能です。",
    backupAndRestore = "バックアップと復元",
    backupDescription = "リンク、設定、APIキーを含むすべてのデータをバックアップします。",
    createBackup = "バックアップを作成",
    restoreBackup = "バックアップを復元",
    backupSuccess = "バックアップが正常に作成されました！",
    restoreSuccess = "データが正常に復元されました！",
    restoreFailed = "バックアップの復元に失敗しました。ファイルを確認してください。",
    backupCreating = "バックアップ作成中...",
    restoreInProgress = "データ復元中...",
    appVersion = "アプリバージョン",
    versionFormat = "バージョン %s (ビルド %s)",
    reSummarize = "再要約",
    analyzingTitle = "分析中...",
    analyzingSummary = "AIがリンクを分析しています...",
    analysisFailedTitle = "分析失敗",
    analysisFailedSummary = "分析に失敗しました: %s"
)

val ChineseSimplifiedStrings = AppStrings(
    language = "zh-CN",
    languageDisplayName = "简体中文",
    appName = "CapyLinker",
    settings = "设置",
    addLink = "添加链接",
    add = "添加",
    apiKeyConfiguration = "Gemini API 配置",
    apiKeyDescription = "输入您的Gemini API密钥以启用AI驱动的链接分析。",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "从Google AI Studio获取API密钥: https://makersuite.google.com/app/apikey",
    saveApiKey = "保存API密钥",
    apiKeySaved = "API密钥已成功保存！",
    modelSettings = "模型设置",
    modelLabel = "Gemini模型",
    modelDescription = "选择用于分析的Gemini模型。",
    languageSettings = "语言设置",
    languageLabel = "语言",
    themeSettings = "主题设置",
    themeLabel = "主题",
    themeSystem = "系统",
    themeLight = "浅色",
    themeDark = "深色",
    clipboardAutoAddLabel = "从剪贴板自动添加",
    clipboardDetected = "检测到URL",
    clipboardMessage = "是否添加剪贴板中的URL？",
    back = "返回",
    cancel = "取消",
    save = "保存",
    enterUrl = "输入要分析的URL:",
    urlPlaceholder = "https://example.com",
    analyzing = "正在使用Gemini AI分析...",
    welcomeMessage = "欢迎使用CapyLinker",
    quotaExceeded = "API配额已超",
    retryLater = "请稍后重试",
    tip = "💡 提示",
    quotaTipMessage = "免费套餐每分钟的请求次数有限。如果达到限制，应用程序将在短暂延迟后自动重试。",
    addLinkDialogDescription = "链接将在后台使用Gemini AI进行分析。",
    urlLabel = "URL",
    linkOptions = "链接选项",
    open = "打开",
    copyUrl = "复制URL",
    share = "分享",
    delete = "删除",
    search = "搜索",
    searchPlaceholder = "搜索链接...",
    noResults = "未找到结果",
    pressBackAgainToExit = "再次按返回键退出",
    notionPageNote = "注意：Notion页面具有动态内容，可能只能提供有限的信息。",
    backupAndRestore = "备份与恢复",
    backupDescription = "备份包括链接、设置和API密钥在内的所有数据。",
    createBackup = "创建备份",
    restoreBackup = "恢复备份",
    backupSuccess = "备份创建成功！",
    restoreSuccess = "数据恢复成功！",
    restoreFailed = "备份恢复失败。请检查文件。",
    backupCreating = "正在创建备份...",
    restoreInProgress = "正在恢复数据...",
    appVersion = "应用版本",
    versionFormat = "版本 %s (构建 %s)",
    reSummarize = "重新总结",
    analyzingTitle = "分析中...",
    analyzingSummary = "AI分析进行中...",
    analysisFailedTitle = "分析失败",
    analysisFailedSummary = "分析失败: %s"
)

val ChineseTraditionalStrings = AppStrings(
    language = "zh-TW",
    languageDisplayName = "繁體中文",
    appName = "CapyLinker",
    settings = "設定",
    addLink = "新增連結",
    add = "新增",
    apiKeyConfiguration = "Gemini API 設定",
    apiKeyDescription = "輸入您的Gemini API金鑰以啟用AI驅動的連結分析。",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "從Google AI Studio取得API金鑰: https://makersuite.google.com/app/apikey",
    saveApiKey = "儲存API金鑰",
    apiKeySaved = "API金鑰已成功儲存！",
    modelSettings = "模型設定",
    modelLabel = "Gemini模型",
    modelDescription = "選擇用於分析的Gemini模型。",
    languageSettings = "語言設定",
    languageLabel = "語言",
    themeSettings = "主題設定",
    themeLabel = "主題",
    themeSystem = "系統",
    themeLight = "淺色",
    themeDark = "深色",
    clipboardAutoAddLabel = "從剪貼簿自動新增",
    clipboardDetected = "偵測到URL",
    clipboardMessage = "是否新增剪貼簿中的URL？",
    back = "返回",
    cancel = "取消",
    save = "儲存",
    enterUrl = "輸入要分析的URL:",
    urlPlaceholder = "https://example.com",
    analyzing = "正在使用Gemini AI分析...",
    welcomeMessage = "歡迎使用CapyLinker",
    quotaExceeded = "API配額已超",
    retryLater = "請稍後重試",
    tip = "💡 提示",
    quotaTipMessage = "免費方案每分鐘的請求次數有限。如果達到限制，應用程式將在短暫延遲後自動重試。",
    addLinkDialogDescription = "連結將在後台使用Gemini AI進行分析。",
    urlLabel = "URL",
    linkOptions = "連結選項",
    open = "開啟",
    copyUrl = "複製URL",
    share = "分享",
    delete = "刪除",
    search = "搜尋",
    searchPlaceholder = "搜尋連結...",
    noResults = "找不到結果",
    pressBackAgainToExit = "再次按返回鍵退出",
    notionPageNote = "注意：Notion頁面具有動態內容，可能只能提供有限的資訊。",
    backupAndRestore = "備份與復原",
    backupDescription = "備份包括連結、設定和API金鑰在內的所有資料。",
    createBackup = "建立備份",
    restoreBackup = "復原備份",
    backupSuccess = "備份建立成功！",
    restoreSuccess = "資料復原成功！",
    restoreFailed = "備份復原失敗。請檢查檔案。",
    backupCreating = "正在建立備份...",
    restoreInProgress = "正在復原資料...",
    appVersion = "應用版本",
    versionFormat = "版本 %s (組建 %s)",
    reSummarize = "重新總結",
    analyzingTitle = "分析中...",
    analyzingSummary = "AI分析進行中...",
    analysisFailedTitle = "分析失敗",
    analysisFailedSummary = "分析失敗: %s"
)

val SpanishStrings = AppStrings(
    language = "es",
    languageDisplayName = "Español",
    appName = "CapyLinker",
    settings = "Configuración",
    addLink = "Agregar enlace",
    add = "Agregar",
    apiKeyConfiguration = "Configuración de Gemini API",
    apiKeyDescription = "Ingrese su clave API de Gemini para habilitar el análisis de enlaces con IA.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Obtén tu clave API de Google AI Studio: https://makersuite.google.com/app/apikey",
    saveApiKey = "Guardar clave API",
    apiKeySaved = "¡Clave API guardada correctamente!",
    modelSettings = "Configuración del modelo",
    modelLabel = "Modelo Gemini",
    modelDescription = "Selecciona el modelo Gemini para usar en el análisis.",
    languageSettings = "Configuración de idioma",
    languageLabel = "Idioma",
    themeSettings = "Configuración de tema",
    themeLabel = "Tema",
    themeSystem = "Sistema",
    themeLight = "Claro",
    themeDark = "Oscuro",
    clipboardAutoAddLabel = "Agregar automáticamente desde portapapeles",
    clipboardDetected = "URL detectada",
    clipboardMessage = "¿Desea agregar esta URL del portapapeles?",
    back = "Atrás",
    cancel = "Cancelar",
    save = "Guardar",
    enterUrl = "Ingrese la URL a analizar:",
    urlPlaceholder = "https://example.com",
    analyzing = "Analizando con Gemini AI...",
    welcomeMessage = "Bienvenido a CapyLinker",
    quotaExceeded = "Cuota de API excedida",
    retryLater = "Por favor, inténtelo de nuevo más tarde",
    tip = "💡 Consejo",
    quotaTipMessage = "El nivel gratuito tiene solicitudes limitadas por minuto. Si alcanza el límite, la aplicación reintentará automáticamente después de un breve retraso.",
    addLinkDialogDescription = "El enlace se analizará en segundo plano usando Gemini AI.",
    urlLabel = "URL",
    linkOptions = "Opciones de enlace",
    open = "Abrir",
    copyUrl = "Copiar URL",
    share = "Compartir",
    delete = "Eliminar",
    search = "Buscar",
    searchPlaceholder = "Buscar enlaces...",
    noResults = "No se encontraron resultados",
    pressBackAgainToExit = "Presiona atrás nuevamente para salir",
    notionPageNote = "Nota: Las páginas de Notion tienen contenido dinámico. Puede haber información limitada disponible.",
    backupAndRestore = "Copia de seguridad y restauración",
    backupDescription = "Realiza una copia de seguridad de todos tus datos, incluidos enlaces, configuraciones y clave API.",
    createBackup = "Crear copia de seguridad",
    restoreBackup = "Restaurar copia de seguridad",
    backupSuccess = "¡Copia de seguridad creada con éxito!",
    restoreSuccess = "¡Datos restaurados con éxito!",
    restoreFailed = "Error al restaurar la copia de seguridad. Por favor, verifica el archivo.",
    backupCreating = "Creando copia de seguridad...",
    restoreInProgress = "Restaurando datos...",
    appVersion = "Versión de la aplicación",
    versionFormat = "Versión %s (Build %s)",
    reSummarize = "Re-resumir",
    analyzingTitle = "Analizando...",
    analyzingSummary = "Análisis de IA en progreso...",
    analysisFailedTitle = "Análisis fallido",
    analysisFailedSummary = "Error al analizar: %s"
)

val FrenchStrings = AppStrings(
    language = "fr",
    languageDisplayName = "Français",
    appName = "CapyLinker",
    settings = "Paramètres",
    addLink = "Ajouter un lien",
    add = "Ajouter",
    apiKeyConfiguration = "Configuration de l'API Gemini",
    apiKeyDescription = "Entrez votre clé API Gemini pour activer l'analyse de liens par IA.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Obtenez votre clé API depuis Google AI Studio: https://makersuite.google.com/app/apikey",
    saveApiKey = "Enregistrer la clé API",
    apiKeySaved = "Clé API enregistrée avec succès !",
    modelSettings = "Paramètres du modèle",
    modelLabel = "Modèle Gemini",
    modelDescription = "Sélectionnez le modèle Gemini à utiliser pour l'analyse.",
    languageSettings = "Paramètres de langue",
    languageLabel = "Langue",
    themeSettings = "Paramètres du thème",
    themeLabel = "Thème",
    themeSystem = "Système",
    themeLight = "Clair",
    themeDark = "Sombre",
    clipboardAutoAddLabel = "Ajouter automatiquement depuis le presse-papiers",
    clipboardDetected = "URL détectée",
    clipboardMessage = "Voulez-vous ajouter cette URL du presse-papiers ?",
    back = "Retour",
    cancel = "Annuler",
    save = "Enregistrer",
    enterUrl = "Entrez l'URL à analyser:",
    urlPlaceholder = "https://example.com",
    analyzing = "Analyse avec Gemini AI...",
    welcomeMessage = "Bienvenue sur CapyLinker",
    quotaExceeded = "Quota API dépassé",
    retryLater = "Veuillez réessayer plus tard",
    tip = "💡 Astuce",
    quotaTipMessage = "Le niveau gratuit a des requêtes limitées par minute. Si vous atteignez la limite, l'application réessayera automatiquement après un court délai.",
    addLinkDialogDescription = "Le lien sera analysé en arrière-plan à l'aide de Gemini AI.",
    urlLabel = "URL",
    linkOptions = "Options du lien",
    open = "Ouvrir",
    copyUrl = "Copier l'URL",
    share = "Partager",
    delete = "Supprimer",
    search = "Rechercher",
    searchPlaceholder = "Rechercher des liens...",
    noResults = "Aucun résultat trouvé",
    pressBackAgainToExit = "Appuyez à nouveau sur retour pour quitter",
    notionPageNote = "Remarque : Les pages Notion ont du contenu dynamique. Des informations limitées peuvent être disponibles.",
    backupAndRestore = "Sauvegarde et restauration",
    backupDescription = "Sauvegardez toutes vos données, y compris les liens, les paramètres et la clé API.",
    createBackup = "Créer une sauvegarde",
    restoreBackup = "Restaurer la sauvegarde",
    backupSuccess = "Sauvegarde créée avec succès !",
    restoreSuccess = "Données restaurées avec succès !",
    restoreFailed = "Échec de la restauration de la sauvegarde. Veuillez vérifier le fichier.",
    backupCreating = "Création de la sauvegarde...",
    restoreInProgress = "Restauration des données...",
    appVersion = "Version de l'application",
    versionFormat = "Version %s (Build %s)",
    reSummarize = "Ré-résumer",
    analyzingTitle = "Analyse en cours...",
    analyzingSummary = "Analyse par IA en cours...",
    analysisFailedTitle = "Analyse échouée",
    analysisFailedSummary = "Échec de l'analyse: %s"
)

val GermanStrings = AppStrings(
    language = "de",
    languageDisplayName = "Deutsch",
    appName = "CapyLinker",
    settings = "Einstellungen",
    addLink = "Link hinzufügen",
    add = "Hinzufügen",
    apiKeyConfiguration = "Gemini API Konfiguration",
    apiKeyDescription = "Geben Sie Ihren Gemini API-Schlüssel ein, um die KI-gestützte Link-Analyse zu aktivieren.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Holen Sie sich Ihren API-Schlüssel von Google AI Studio: https://makersuite.google.com/app/apikey",
    saveApiKey = "API-Schlüssel speichern",
    apiKeySaved = "API-Schlüssel erfolgreich gespeichert!",
    modelSettings = "Modelleinstellungen",
    modelLabel = "Gemini-Modell",
    modelDescription = "Wählen Sie das Gemini-Modell für die Analyse aus.",
    languageSettings = "Spracheinstellungen",
    languageLabel = "Sprache",
    themeSettings = "Themeneinstellungen",
    themeLabel = "Thema",
    themeSystem = "System",
    themeLight = "Hell",
    themeDark = "Dunkel",
    clipboardAutoAddLabel = "Automatisch aus Zwischenablage hinzufügen",
    clipboardDetected = "URL erkannt",
    clipboardMessage = "Möchten Sie diese URL aus der Zwischenablage hinzufügen?",
    back = "Zurück",
    cancel = "Abbrechen",
    save = "Speichern",
    enterUrl = "Geben Sie die zu analysierende URL ein:",
    urlPlaceholder = "https://example.com",
    analyzing = "Analyse mit Gemini AI...",
    welcomeMessage = "Willkommen bei CapyLinker",
    quotaExceeded = "API-Kontingent überschritten",
    retryLater = "Bitte versuchen Sie es später erneut",
    tip = "💡 Tipp",
    quotaTipMessage = "Die kostenlose Stufe hat begrenzte Anfragen pro Minute. Wenn Sie das Limit erreichen, wird die App nach einer kurzen Verzögerung automatisch erneut versuchen.",
    addLinkDialogDescription = "Der Link wird im Hintergrund mit Gemini AI analysiert.",
    urlLabel = "URL",
    linkOptions = "Link-Optionen",
    open = "Öffnen",
    copyUrl = "URL kopieren",
    share = "Teilen",
    delete = "Löschen",
    search = "Suchen",
    searchPlaceholder = "Links suchen...",
    noResults = "Keine Ergebnisse gefunden",
    pressBackAgainToExit = "Drücken Sie erneut zurück, um zu beenden",
    notionPageNote = "Hinweis: Notion-Seiten haben dynamische Inhalte. Möglicherweise sind nur begrenzte Informationen verfügbar.",
    backupAndRestore = "Sicherung und Wiederherstellung",
    backupDescription = "Sichern Sie alle Ihre Daten, einschließlich Links, Einstellungen und API-Schlüssel.",
    createBackup = "Sicherung erstellen",
    restoreBackup = "Sicherung wiederherstellen",
    backupSuccess = "Sicherung erfolgreich erstellt!",
    restoreSuccess = "Daten erfolgreich wiederhergestellt!",
    restoreFailed = "Fehler beim Wiederherstellen der Sicherung. Bitte überprüfen Sie die Datei.",
    backupCreating = "Sicherung wird erstellt...",
    restoreInProgress = "Daten werden wiederhergestellt...",
    appVersion = "App-Version",
    versionFormat = "Version %s (Build %s)",
    reSummarize = "Erneut zusammenfassen",
    analyzingTitle = "Analysiere...",
    analyzingSummary = "KI-Analyse läuft...",
    analysisFailedTitle = "Analyse fehlgeschlagen",
    analysisFailedSummary = "Analyse fehlgeschlagen: %s"
)

val RussianStrings = AppStrings(
    language = "ru",
    languageDisplayName = "Русский",
    appName = "CapyLinker",
    settings = "Настройки",
    addLink = "Добавить ссылку",
    add = "Добавить",
    apiKeyConfiguration = "Конфигурация Gemini API",
    apiKeyDescription = "Введите ключ API Gemini для активации анализа ссылок с помощью ИИ.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Получите ключ API в Google AI Studio: https://makersuite.google.com/app/apikey",
    saveApiKey = "Сохранить ключ API",
    apiKeySaved = "Ключ API успешно сохранён!",
    modelSettings = "Настройки модели",
    modelLabel = "Модель Gemini",
    modelDescription = "Выберите модель Gemini для использования в анализе.",
    languageSettings = "Настройки языка",
    languageLabel = "Язык",
    themeSettings = "Настройки темы",
    themeLabel = "Тема",
    themeSystem = "Система",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    clipboardAutoAddLabel = "Автоматически добавлять из буфера обмена",
    clipboardDetected = "URL обнаружен",
    clipboardMessage = "Добавить этот URL из буфера обмена?",
    back = "Назад",
    cancel = "Отмена",
    save = "Сохранить",
    enterUrl = "Введите URL для анализа:",
    urlPlaceholder = "https://example.com",
    analyzing = "Анализ с помощью Gemini AI...",
    welcomeMessage = "Добро пожаловать в CapyLinker",
    quotaExceeded = "Превышена квота API",
    retryLater = "Пожалуйста, попробуйте позже",
    tip = "💡 Совет",
    quotaTipMessage = "Бесплатный тариф имеет ограниченное количество запросов в минуту. Если вы достигнете лимита, приложение автоматически повторит попытку после короткой задержки.",
    addLinkDialogDescription = "Ссылка будет проанализирована в фоновом режиме с помощью Gemini AI.",
    urlLabel = "URL",
    linkOptions = "Опции ссылки",
    open = "Открыть",
    copyUrl = "Копировать URL",
    share = "Поделиться",
    delete = "Удалить",
    search = "Поиск",
    searchPlaceholder = "Поиск ссылок...",
    noResults = "Результаты не найдены",
    pressBackAgainToExit = "Нажмите назад еще раз, чтобы выйти",
    notionPageNote = "Примечание: страницы Notion имеют динамический контент. Может быть доступна ограниченная информация.",
    backupAndRestore = "Резервное копирование и восстановление",
    backupDescription = "Создайте резервную копию всех ваших данных, включая ссылки, настройки и ключ API.",
    createBackup = "Создать резервную копию",
    restoreBackup = "Восстановить из резервной копии",
    backupSuccess = "Резервная копия успешно создана!",
    restoreSuccess = "Данные успешно восстановлены!",
    restoreFailed = "Не удалось восстановить резервную копию. Пожалуйста, проверьте файл.",
    backupCreating = "Создание резервной копии...",
    restoreInProgress = "Восстановление данных...",
    appVersion = "Версия приложения",
    versionFormat = "Версия %s (Сборка %s)",
    reSummarize = "Пересказать",
    analyzingTitle = "Анализ...",
    analyzingSummary = "Анализ ИИ в процессе...",
    analysisFailedTitle = "Ошибка анализа",
    analysisFailedSummary = "Не удалось проанализировать: %s"
)

val PortugueseStrings = AppStrings(
    language = "pt",
    languageDisplayName = "Português",
    appName = "CapyLinker",
    settings = "Configurações",
    addLink = "Adicionar link",
    add = "Adicionar",
    apiKeyConfiguration = "Configuração da API Gemini",
    apiKeyDescription = "Digite sua chave API Gemini para ativar a análise de links com IA.",
    apiKeyLabel = "Gemini API Key",
    apiKeyPlaceholder = "AIza...",
    apiKeyHint = "Obtenha sua chave API do Google AI Studio: https://makersuite.google.com/app/apikey",
    saveApiKey = "Salvar chave API",
    apiKeySaved = "Chave API salva com sucesso!",
    modelSettings = "Configurações do modelo",
    modelLabel = "Modelo Gemini",
    modelDescription = "Selecione o modelo Gemini para usar na análise.",
    languageSettings = "Configurações de idioma",
    languageLabel = "Idioma",
    themeSettings = "Configurações de tema",
    themeLabel = "Tema",
    themeSystem = "Sistema",
    themeLight = "Claro",
    themeDark = "Escuro",
    clipboardAutoAddLabel = "Adicionar automaticamente da área de transferência",
    clipboardDetected = "URL detectada",
    clipboardMessage = "Deseja adicionar esta URL da área de transferência?",
    back = "Voltar",
    cancel = "Cancelar",
    save = "Salvar",
    enterUrl = "Digite a URL para analisar:",
    urlPlaceholder = "https://example.com",
    analyzing = "Analisando com Gemini AI...",
    welcomeMessage = "Bem-vindo ao CapyLinker",
    quotaExceeded = "Cota da API excedida",
    retryLater = "Por favor, tente novamente mais tarde",
    tip = "💡 Dica",
    quotaTipMessage = "O nível gratuito tem solicitações limitadas por minuto. Se você atingir o limite, o aplicativo tentará novamente automaticamente após um breve atraso.",
    addLinkDialogDescription = "O link será analisado em segundo plano usando Gemini AI.",
    urlLabel = "URL",
    linkOptions = "Opções do link",
    open = "Abrir",
    copyUrl = "Copiar URL",
    share = "Compartilhar",
    delete = "Excluir",
    search = "Pesquisar",
    searchPlaceholder = "Pesquisar links...",
    noResults = "Nenhum resultado encontrado",
    pressBackAgainToExit = "Pressione voltar novamente para sair",
    notionPageNote = "Nota: As páginas do Notion têm conteúdo dinâmico. Informações limitadas podem estar disponíveis.",
    backupAndRestore = "Backup e restauração",
    backupDescription = "Faça backup de todos os seus dados, incluindo links, configurações e chave API.",
    createBackup = "Criar backup",
    restoreBackup = "Restaurar backup",
    backupSuccess = "Backup criado com sucesso!",
    restoreSuccess = "Dados restaurados com sucesso!",
    restoreFailed = "Falha ao restaurar backup. Por favor, verifique o arquivo.",
    backupCreating = "Criando backup...",
    restoreInProgress = "Restaurando dados...",
    appVersion = "Versão do aplicativo",
    versionFormat = "Versão %s (Build %s)",
    reSummarize = "Re-resumir",
    analyzingTitle = "Analisando...",
    analyzingSummary = "Análise de IA em andamento...",
    analysisFailedTitle = "Falha na análise",
    analysisFailedSummary = "Falha ao analisar: %s"
)

fun getStrings(language: String): AppStrings {
    return when (language) {
        "ko" -> KoreanStrings
        "ja" -> JapaneseStrings
        "zh-CN" -> ChineseSimplifiedStrings
        "zh-TW" -> ChineseTraditionalStrings
        "es" -> SpanishStrings
        "fr" -> FrenchStrings
        "de" -> GermanStrings
        "ru" -> RussianStrings
        "pt" -> PortugueseStrings
        "en" -> EnglishStrings
        else -> EnglishStrings // 기본값을 영어로 설정
    }
}
